# Dataset configuration
dataset_type: "waymo"
waymo_path: "data/waymo_mini"
waymo_component: "camera_image"
sequence_ids: null  # null means load all sequences, or provide list like ["segment_id_1", "segment_id_2"]

# Training configuration
batch_size: 4
num_workers: 4
epochs: 1 #50
n_frames: 2
image_size: [128, 128]

# Optimizer configuration
optimizer:
  lr: 0.0001
  weight_decay: 0.01

# Scheduler configuration
scheduler:
  T_max: 50
  eta_min: 0.000001

# Device
device: "cuda"

# Metadata dropout (for co3d, not used in waymo)
metadata_dropout: 0.5